import { DateTime } from "luxon";
import { feedPlugin } from "@11ty/eleventy-plugin-rss";

export default function (eleventyConfig) {
  eleventyConfig.setInputDirectory("src");
  eleventyConfig.setOutputDirectory(".");
  eleventyConfig.setIncludesDirectory("_includes");
  eleventyConfig.setDataDirectory("_data");

  // Existing static assets already live at the repo root and are served
  // as-is by GitHub Pages — Eleventy only generates the HTML.
  eleventyConfig.setTemplateFormats(["njk", "md"]);
  eleventyConfig.addGlobalData("layout", "base.njk");

  // ---- Filters -------------------------------------------------------------

  eleventyConfig.addFilter("isoDate", (d) => DateTime.fromJSDate(d, { zone: "utc" }).toISO());
  eleventyConfig.addFilter("readableDate", (d) =>
    DateTime.fromJSDate(d, { zone: "utc" }).toFormat("LLLL d, yyyy"),
  );
  eleventyConfig.addFilter("year", (d) => DateTime.fromJSDate(d, { zone: "utc" }).toFormat("yyyy"));
  eleventyConfig.addFilter("jsonld", (obj) => JSON.stringify(obj, null, 2));
  eleventyConfig.addFilter("pad2", (n) => String(n).padStart(2, "0"));
  eleventyConfig.addFilter("endsWith", (s, suffix) => String(s).endsWith(suffix));

  // Words / 200 wpm, rounded up, floored at 1.
  eleventyConfig.addFilter("readingTime", (text) => {
    const words = String(text)
      .replace(/<[^>]+>/g, " ")
      .split(/\s+/)
      .filter(Boolean).length;
    return Math.max(1, Math.round(words / 200));
  });

  // Strip HTML for meta descriptions / word counts.
  eleventyConfig.addFilter("striptags", (s) => String(s).replace(/<[^>]+>/g, ""));

  // ---- Responsive image shortcode -----------------------------------------
  // Emits a <picture> with webp + jpg, a responsive srcset (variants are
  // pre-generated by scripts/build-assets.mjs), and intrinsic dimensions.
  // Usage: {% figure "luqman/01-hero", "Alt text", 1600, 1250 %}
  //        {% figure "luqman/01-hero", "Alt text", 1600, 1250, "eager" %}
  const IMG_WIDTHS = [640, 960, 1280];
  eleventyConfig.addShortcode(
    "figure",
    (slug, alt, w, h, loading = "lazy", sizes = "(min-width: 1000px) 1000px, 100vw") => {
      const base = `/assets/images/${slug}`;
      const set = (ext) =>
        [
          ...IMG_WIDTHS.filter((x) => x < w).map((x) => `${base}-${x}.${ext} ${x}w`),
          `${base}.${ext} ${w}w`,
        ].join(", ");
      const eager = loading === "eager";
      const imgAttrs = eager
        ? 'fetchpriority="high" decoding="async"'
        : 'loading="lazy" decoding="async"';
      return `<picture>
  <source type="image/webp" srcset="${set("webp")}" sizes="${sizes}">
  <img src="${base}.jpg" srcset="${set("jpg")}" sizes="${sizes}" width="${w}" height="${h}" alt="${alt}" ${imgAttrs}>
</picture>`;
    },
  );

  // ---- Collections ------------------------------------------------------------

  eleventyConfig.addCollection("post", (api) =>
    api.getFilteredByTag("post").sort((a, b) => b.date - a.date),
  );
  eleventyConfig.addCollection("caseStudy", (api) =>
    api.getFilteredByTag("caseStudy").sort((a, b) => (a.data.order || 0) - (b.data.order || 0)),
  );

  // ---- RSS ------------------------------------------------------------------

  eleventyConfig.addPlugin(feedPlugin, {
    type: "atom",
    outputPath: "/feed.xml",
    collection: { name: "post", limit: 20 },
    metadata: {
      language: "en",
      title: "Zed Alleys — Journal",
      subtitle: "Design writing and essays by Ziad Fteha.",
      base: "https://zedalleys.com/",
      author: { name: "Ziad Fteha", email: "ziadfteha@gmail.com" },
    },
  });

  eleventyConfig.setServerOptions({ port: 8080 });

  return {
    htmlTemplateEngine: "njk",
    markdownTemplateEngine: "njk",
  };
}
